### ISSUE TITLE
Can't install avored-related using composer

### ISSUE THREAD

**Issue by belguinan** [avored/related#1]
Hello,

C:\xampp7.1\htdocs\avored\laravel-ecommerce>composer require avored/related
  [InvalidArgumentException]
  Could not find package avored/related at any version for your minimum-stability (stable). Check the package spelling or your minimum-stability

Composer can't find the package

**Comment by indpurvesh** [comment]
Open your composer.json file and put avored related repository as dev-master then execute `composer update` command

    "avored/related": "dev-master"

Execute Below Command

    composer update
